name: scribble_etome
description: "A flutter plugin to integrate scribble sdk of jzztech to flutter app"
version: 1.0.3
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.leywin.scribble_etome
        pluginClass: ScribbleEtomePlugin